config/routes.rb
Depot::Application.routes.draw do
  match "settings" => "settings#index"
  match "admin" => "admin#index"

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  get "home/index"
  get "classifies/index"

  root :to => 'home#index' 

end

app/views/common/_flashes.html.erb
<%
 f = {:notice =>  "alert-success",
      :error => "alert-error",
      :alert => 'alert-message'
 }
%>
<% [:notice, :error, :alert].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="<%= f[level] %> alert fade in" data-alert="alert">
      <a class="close" data-dismiss="alert" href="#">×</a>
      <%= content_tag :p, flash[level] %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<p style="text-align: center;margin-top:30px;">Depot on Rails by <a href="#">foyoto</a>. ytfang © biencloud 2012</p>

app/views/common/_header.html.erb
<h1><%= content_for?(:title) ? yield(:title) : 'Depot on Rails' %></h1>

app/views/common/_menu.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%
         menus = []
         menus << content_tag('li', link_to("首页",root_path))
         menus << content_tag('li', link_to("博客",posts_path)) if user_signed_in?
      %>
      <ul class="nav" id="menu">
        <%= menus.join("<li class='divider-vertical'></li>").html_safe %>
      </ul>

      <form method="post" id="post_search" class="navbar-search pull-left" action="/posts/index" accept-charset="UTF-8"><div style="margin: 0pt; padding: 0pt; display: inline;"><input type="hidden" value="✓" name="utf8"><input type="hidden" value="uueVFd+hFk8uwlW4LoKWR3xOjtHPEdwU1pT5x6IwIns=" name="authenticity_token"></div>
        <input type="text" size="30" placeholder="Search" name="search[title_contains]" id="search_title_contains" class="search-query span2"><br>
      </form>

      <ul class="nav pull-right">
        <% if user_signed_in? -%>
            <li><%= link_to current_user.email, edit_user_registration_path %></li>
            <li><%= link_to '管理', admin_path %></li>
            <li class="divider-vertical"></li>
            <li><%= link_to '退出登录', destroy_user_session_path, :method => :delete %></li>
        <% else %>
            <li><%= link_to '注册', new_user_registration_path %></li>
            <li><%= link_to '登录', new_user_session_path %></li>
        <% end -%>
      </ul>
    </div>
  </div>
</div>

app/views/common/_tag_cloud.html.erb
<p>
  <b>标签:</b>
  <% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <%= link_to tag.name, {:action => "tag_cloud",:id => tag.name,:page=>params[:page]}, :class => css_class %>
  <% end %>
  <style type="text/css">
      .css1 { font-size: 1.0em;color:#F00 !important; }
      .css2 { font-size: 1.2em;color:#0F0 !important; }
      .css3 { font-size: 1.4em;color:#00F !important; }
      .css4 { font-size: 1.6em;color:#000 !important; }
  </style>
</p>

app/views/common/_tag_form.html.erb
<%= form.input :tag_list %>